import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "@/node_modules/next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Animal Rescue Shelter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex flex-col items-center justify-center p-14">
          <ul className="flex text-lg gap-4">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/adoption">Adoption</Link>
            </li>
            <li>
              <Link href="/getInvolved">Get Involved</Link>
            </li>
            <li>
              <Link href="/educationalResources">Educational Resources</Link>
            </li>
            <li>
              <Link href="/contactUs">Contact Us</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
