import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "@/node_modules/next/link";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";

const pages: Record<string, `/${string}`> = {
  Home: "/",
  Adoption: "/adoption",
  ContactUs: "/contactUs",
  EducationalResources: "/educationalResources",
  GetInvolved: "/getInvolved",
  // Blog: "/blog",
  // Users: "/users",
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Animal Rescue Shelter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar pages={pages} />
        {children}
        <Footer pages={pages} />
      </body>
    </html>
  );
}
